
import type { Metadata } from "next";

import "./globals.css";
 import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/lib/hooks/authContext";
import { usePathname } from "next/navigation";
import Footer_Mob from "@/components/Footer_Mob";

export const metadata: Metadata = {
  title: "Rentgara",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <AuthProvider protectedRoutes={[]}>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
