
import type { Metadata } from "next";

import "./globals.css";
 import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/lib/hooks/authContext";

export const metadata: Metadata = {
  title: "Rentgara",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
